import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"组件概览","description":"","frontmatter":{},"headers":[],"relativePath":"components/overview.md","filePath":"components/overview.md"}');
const _sfc_main = { name: "components/overview.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="组件概览" tabindex="-1">组件概览 <a class="header-anchor" href="#组件概览" aria-label="Permalink to &quot;组件概览&quot;">​</a></h1><p>Kupola 的组件按能力分组维护，所有组件都支持主包引入和按需引入。公开库使用时推荐按需引入，配合 <code>@kupola/kupola/css</code> 或 <code>@kupola/kupola/css/components</code> 使用库内置样式。</p><h2 id="安装" tabindex="-1">安装 <a class="header-anchor" href="#安装" aria-label="Permalink to &quot;安装&quot;">​</a></h2><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> install</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> @kupola/kupola</span></span></code></pre></div><h2 id="引入方式" tabindex="-1">引入方式 <a class="header-anchor" href="#引入方式" aria-label="Permalink to &quot;引入方式&quot;">​</a></h2><div class="language-js vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">js</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &#39;@kupola/kupola/css&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// 完整入口</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> { Modal, Table, Form } </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &#39;@kupola/kupola&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// 按需入口</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> { Modal } </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &#39;@kupola/kupola/components/modal&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> { Table } </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &#39;@kupola/kupola/components/table&#39;</span></span></code></pre></div><h2 id="分类导航" tabindex="-1">分类导航 <a class="header-anchor" href="#分类导航" aria-label="Permalink to &quot;分类导航&quot;">​</a></h2><table tabindex="0"><thead><tr><th>分类</th><th>组件</th><th>说明</th></tr></thead><tbody><tr><td><a href="/kupola/components/overlay.html">覆盖层</a></td><td>Modal, Dropdown, Drawer, Dialog, Notification, Tooltip</td><td>弹窗、抽屉、浮层、全局通知</td></tr><tr><td><a href="/kupola/components/navigation.html">导航</a></td><td>Tabs, Pagination, Datepicker, Breadcrumb, Menu, Calendar</td><td>页面切换、分页、日期与路径导航</td></tr><tr><td><a href="/kupola/components/forms.html">表单</a></td><td>Form, Input, Select, Checkbox, Radio, Switch, Slider, NumberInput, Textarea, Timepicker, Validation</td><td>输入、选择、校验和表单数据管理</td></tr><tr><td><a href="/kupola/components/feedback.html">反馈</a></td><td>Alert, Progress, Skeleton, Spin, Empty, Countdown</td><td>状态反馈、加载、空态和倒计时</td></tr><tr><td><a href="/kupola/components/display.html">展示</a></td><td>Tag, Badge, Divider, Collapse, Timeline, Kbd, Avatar, Statcard, Tree, Carousel</td><td>信息展示、数据层级、折叠面板和内容轮播</td></tr><tr><td><a href="/kupola/components/interaction.html">交互</a></td><td>FileUpload, DynamicTags, ImagePreview, ColorPicker, VirtualList</td><td>文件、标签、图片、颜色和大数据列表</td></tr><tr><td><a href="/kupola/components/tools.html">工具</a></td><td>Icons, Message, Heatmap, Table</td><td>图标、全局消息、热力图和数据表格</td></tr></tbody></table><h2 id="重点文档" tabindex="-1">重点文档 <a class="header-anchor" href="#重点文档" aria-label="Permalink to &quot;重点文档&quot;">​</a></h2><ul><li><a href="/kupola/components/modal.html">Modal</a>: 可控模态框，支持遮罩关闭、ESC 关闭和聚焦管理。</li><li><a href="/kupola/components/form.html">Form</a>: 表单字段收集、校验、数据读写和提交处理。</li><li><a href="/kupola/components/table.html">Table</a>: 数据表格，支持分页、排序、筛选、选择、树表和行编辑。</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("components/overview.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const overview = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  overview as default
};
